version: '3.8'

services:
  mem_eater_1:
    image: mauriciohc/mem-eater
    container_name: mem_cont_1
  mem_eater_2:
    image: mauriciohc/mem-eater
    container_name: mem_cont_2
  mem_eater_3:
    image: mauriciohc/mem-eater
    container_name: mem_cont_3
